name: 'Hello World'
description: 'Generating stats about first-time contributions. Make your open source project truly welcoming to them'
author: 'Trang Le <trang.thule@zoho.com>'

runs:
  using: 'node12'
  main: 'index.js'