name: "Hello World"

on: [push, pull_request]

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Hello world action step
        uses: ./
        with:
          character: bender
        id: futurama
      - name: After Hello World
        run: echo ${{steps.futurama.outputs.quote}}